version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
  app:
    build: ./server
    container_name: node-app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # volumes:
    #   - .:/usr/src/app
    # command: ["node", "server/index.js"]
