version: "3.8"

services:
  redis-node-1:
    image: redis:latest
    container_name: redis-1
    ports:
      - "6380:6379"

  redis-node-2:
    image: redis:latest
    container_name: redis-2
    ports:
      - "6381:6379"

  redis-node-3:
    image: redis:latest
    container_name: redis-3
    ports:
      - "6382:6379"

  app:
    build: ./server
    container_name: node-app
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    environment:
      - REDIS_NODES=redis-node1:6379,redis-node-2:6379,redis-node-3:6379
